(cl:defpackage cw3_helper-srv
  (:use )
  (:export
   "CHANGECOLLISIONOBJECT"
   "<CHANGECOLLISIONOBJECT-REQUEST>"
   "CHANGECOLLISIONOBJECT-REQUEST"
   "<CHANGECOLLISIONOBJECT-RESPONSE>"
   "CHANGECOLLISIONOBJECT-RESPONSE"
  ))

