#sat:
# Imaging iiwa -----------------------------------
  eye_iiwa_joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 500  

  eye_iiwa_PositionJointInterface_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - eye_iiwa_joint_1
      - eye_iiwa_joint_2
      - eye_iiwa_joint_3
      - eye_iiwa_joint_4
      - eye_iiwa_joint_5
      - eye_iiwa_joint_6
      - eye_iiwa_joint_7

    constraints:
      goal_time: 0.5                   # Override default

    state_publish_rate:  500            # Override default
    action_monitor_rate: 500            # Override default
    stop_trajectory_duration: 0        # Override default
    
# Hand iiwa -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 500  

  PositionJointInterface_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - sr_iiwa_joint_1
      - sr_iiwa_joint_2
      - sr_iiwa_joint_3
      - sr_iiwa_joint_4
      - sr_iiwa_joint_5
      - sr_iiwa_joint_6
      - sr_iiwa_joint_7

    constraints:
      goal_time: 0.5                   # Override default

    state_publish_rate:  500            # Override default
    action_monitor_rate: 500            # Override default
    stop_trajectory_duration: 0        # Override default
    
