controller_list:
  - name: fake_ff_kuka_controller
    joints:
      - hand_iiwa_joint_1
      - hand_iiwa_joint_2
      - hand_iiwa_joint_3
      - hand_iiwa_joint_4
      - hand_iiwa_joint_5
      - hand_iiwa_joint_6
      - hand_iiwa_joint_7
      - lh_FFJ4
      - lh_FFJ3
      - lh_FFJ2
      - lh_FFJ1
  - name: fake_mf_kuka_controller
    joints:
      - hand_iiwa_joint_1
      - hand_iiwa_joint_2
      - hand_iiwa_joint_3
      - hand_iiwa_joint_4
      - hand_iiwa_joint_5
      - hand_iiwa_joint_6
      - hand_iiwa_joint_7
      - lh_MFJ4
      - lh_MFJ3
      - lh_MFJ2
      - lh_MFJ1
  - name: fake_rf_kuka_controller
    joints:
      - hand_iiwa_joint_1
      - hand_iiwa_joint_2
      - hand_iiwa_joint_3
      - hand_iiwa_joint_4
      - hand_iiwa_joint_5
      - hand_iiwa_joint_6
      - hand_iiwa_joint_7
      - lh_RFJ4
      - lh_RFJ3
      - lh_RFJ2
      - lh_RFJ1
  - name: fake_th_kuka_controller
    joints:
      - hand_iiwa_joint_1
      - hand_iiwa_joint_2
      - hand_iiwa_joint_3
      - hand_iiwa_joint_4
      - hand_iiwa_joint_5
      - hand_iiwa_joint_6
      - hand_iiwa_joint_7
      - lh_THJ5
      - lh_THJ4
      - lh_THJ2
      - lh_THJ1
  - name: fake_Robot_controller
    joints:
      - hand_iiwa_joint_1
      - hand_iiwa_joint_2
      - hand_iiwa_joint_3
      - hand_iiwa_joint_4
      - hand_iiwa_joint_5
      - hand_iiwa_joint_6
      - hand_iiwa_joint_7
      - lh_FFJ4
      - lh_FFJ3
      - lh_FFJ2
      - lh_FFJ1
      - lh_MFJ4
      - lh_MFJ3
      - lh_MFJ2
      - lh_MFJ1
      - lh_RFJ4
      - lh_RFJ3
      - lh_RFJ2
      - lh_RFJ1
      - lh_THJ5
      - lh_THJ4
      - lh_THJ2
      - lh_THJ1
  - name: fake_Kuka_controller
    joints:
      - hand_iiwa_joint_1
      - hand_iiwa_joint_2
      - hand_iiwa_joint_3
      - hand_iiwa_joint_4
      - hand_iiwa_joint_5
      - hand_iiwa_joint_6
      - hand_iiwa_joint_7
  - name: fake_palm_controller
    joints:
      - hand_iiwa_joint_1
      - hand_iiwa_joint_2
      - hand_iiwa_joint_3
      - hand_iiwa_joint_4
      - hand_iiwa_joint_5
      - hand_iiwa_joint_6
      - hand_iiwa_joint_7