// Generated by gencpp from file AW_hand_service/moveObj.msg
// DO NOT EDIT!


#ifndef AW_HAND_SERVICE_MESSAGE_MOVEOBJ_H
#define AW_HAND_SERVICE_MESSAGE_MOVEOBJ_H

#include <ros/service_traits.h>


#include <AW_hand_service/moveObjRequest.h>
#include <AW_hand_service/moveObjResponse.h>


namespace AW_hand_service
{

struct moveObj
{

typedef moveObjRequest Request;
typedef moveObjResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct moveObj
} // namespace AW_hand_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::AW_hand_service::moveObj > {
  static const char* value()
  {
    return "e273575340e93981085e010f5e57043f";
  }

  static const char* value(const ::AW_hand_service::moveObj&) { return value(); }
};

template<>
struct DataType< ::AW_hand_service::moveObj > {
  static const char* value()
  {
    return "AW_hand_service/moveObj";
  }

  static const char* value(const ::AW_hand_service::moveObj&) { return value(); }
};


// service_traits::MD5Sum< ::AW_hand_service::moveObjRequest> should match 
// service_traits::MD5Sum< ::AW_hand_service::moveObj > 
template<>
struct MD5Sum< ::AW_hand_service::moveObjRequest>
{
  static const char* value()
  {
    return MD5Sum< ::AW_hand_service::moveObj >::value();
  }
  static const char* value(const ::AW_hand_service::moveObjRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::AW_hand_service::moveObjRequest> should match 
// service_traits::DataType< ::AW_hand_service::moveObj > 
template<>
struct DataType< ::AW_hand_service::moveObjRequest>
{
  static const char* value()
  {
    return DataType< ::AW_hand_service::moveObj >::value();
  }
  static const char* value(const ::AW_hand_service::moveObjRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::AW_hand_service::moveObjResponse> should match 
// service_traits::MD5Sum< ::AW_hand_service::moveObj > 
template<>
struct MD5Sum< ::AW_hand_service::moveObjResponse>
{
  static const char* value()
  {
    return MD5Sum< ::AW_hand_service::moveObj >::value();
  }
  static const char* value(const ::AW_hand_service::moveObjResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::AW_hand_service::moveObjResponse> should match 
// service_traits::DataType< ::AW_hand_service::moveObj > 
template<>
struct DataType< ::AW_hand_service::moveObjResponse>
{
  static const char* value()
  {
    return DataType< ::AW_hand_service::moveObj >::value();
  }
  static const char* value(const ::AW_hand_service::moveObjResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AW_HAND_SERVICE_MESSAGE_MOVEOBJ_H
