blacklist:
- trac_ik
- trac_ik_examples
- trac_ik_kinematics_plugin
build_space: build
catkin_make_args: []
cmake_args:
- -DPYTHON_EXECUTABLE=/usr/bin/python3
- -DPYTHON_VERSION=3
- -DCMAKE_BUILD_TYPE=Release
devel_layout: merged
devel_space: devel
extend_path: /usr
install: true
install_space: install
isolate_install: false
jobs_args: []
log_space: logs
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
