// Generated by gencpp from file sr_robot_msgs/ForceControllerResponse.msg
// DO NOT EDIT!


#ifndef SR_ROBOT_MSGS_MESSAGE_FORCECONTROLLERRESPONSE_H
#define SR_ROBOT_MSGS_MESSAGE_FORCECONTROLLERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sr_robot_msgs
{
template <class ContainerAllocator>
struct ForceControllerResponse_
{
  typedef ForceControllerResponse_<ContainerAllocator> Type;

  ForceControllerResponse_()
    : configured(false)  {
    }
  ForceControllerResponse_(const ContainerAllocator& _alloc)
    : configured(false)  {
  (void)_alloc;
    }



   typedef uint8_t _configured_type;
  _configured_type configured;





  typedef boost::shared_ptr< ::sr_robot_msgs::ForceControllerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sr_robot_msgs::ForceControllerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ForceControllerResponse_

typedef ::sr_robot_msgs::ForceControllerResponse_<std::allocator<void> > ForceControllerResponse;

typedef boost::shared_ptr< ::sr_robot_msgs::ForceControllerResponse > ForceControllerResponsePtr;
typedef boost::shared_ptr< ::sr_robot_msgs::ForceControllerResponse const> ForceControllerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sr_robot_msgs::ForceControllerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sr_robot_msgs::ForceControllerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sr_robot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'shape_msgs': ['/opt/ros/kinetic/share/shape_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'moveit_msgs': ['/opt/ros/kinetic/share/moveit_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/kinetic/share/object_recognition_msgs/cmake/../msg'], 'octomap_msgs': ['/opt/ros/kinetic/share/octomap_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sr_robot_msgs': ['/home/mamad/Demo/demo/src/iiwa_pybullet_integration/shadow_dep/sr_common/sr_robot_msgs/msg', '/home/mamad/Demo/demo/devel/share/sr_robot_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sr_robot_msgs::ForceControllerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sr_robot_msgs::ForceControllerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sr_robot_msgs::ForceControllerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sr_robot_msgs::ForceControllerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sr_robot_msgs::ForceControllerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sr_robot_msgs::ForceControllerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sr_robot_msgs::ForceControllerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d3b1a74026985b10664594fe60a8c3eb";
  }

  static const char* value(const ::sr_robot_msgs::ForceControllerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd3b1a74026985b10ULL;
  static const uint64_t static_value2 = 0x664594fe60a8c3ebULL;
};

template<class ContainerAllocator>
struct DataType< ::sr_robot_msgs::ForceControllerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sr_robot_msgs/ForceControllerResponse";
  }

  static const char* value(const ::sr_robot_msgs::ForceControllerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sr_robot_msgs::ForceControllerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool configured\n\
";
  }

  static const char* value(const ::sr_robot_msgs::ForceControllerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sr_robot_msgs::ForceControllerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.configured);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ForceControllerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sr_robot_msgs::ForceControllerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sr_robot_msgs::ForceControllerResponse_<ContainerAllocator>& v)
  {
    s << indent << "configured: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.configured);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SR_ROBOT_MSGS_MESSAGE_FORCECONTROLLERRESPONSE_H
