// Generated by gencpp from file sr_robot_msgs/GetFastGraspFromBoundingBox.msg
// DO NOT EDIT!


#ifndef SR_ROBOT_MSGS_MESSAGE_GETFASTGRASPFROMBOUNDINGBOX_H
#define SR_ROBOT_MSGS_MESSAGE_GETFASTGRASPFROMBOUNDINGBOX_H

#include <ros/service_traits.h>


#include <sr_robot_msgs/GetFastGraspFromBoundingBoxRequest.h>
#include <sr_robot_msgs/GetFastGraspFromBoundingBoxResponse.h>


namespace sr_robot_msgs
{

struct GetFastGraspFromBoundingBox
{

typedef GetFastGraspFromBoundingBoxRequest Request;
typedef GetFastGraspFromBoundingBoxResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetFastGraspFromBoundingBox
} // namespace sr_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sr_robot_msgs::GetFastGraspFromBoundingBox > {
  static const char* value()
  {
    return "ffbffca6a4c0c33cabde5517cccd453b";
  }

  static const char* value(const ::sr_robot_msgs::GetFastGraspFromBoundingBox&) { return value(); }
};

template<>
struct DataType< ::sr_robot_msgs::GetFastGraspFromBoundingBox > {
  static const char* value()
  {
    return "sr_robot_msgs/GetFastGraspFromBoundingBox";
  }

  static const char* value(const ::sr_robot_msgs::GetFastGraspFromBoundingBox&) { return value(); }
};


// service_traits::MD5Sum< ::sr_robot_msgs::GetFastGraspFromBoundingBoxRequest> should match 
// service_traits::MD5Sum< ::sr_robot_msgs::GetFastGraspFromBoundingBox > 
template<>
struct MD5Sum< ::sr_robot_msgs::GetFastGraspFromBoundingBoxRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sr_robot_msgs::GetFastGraspFromBoundingBox >::value();
  }
  static const char* value(const ::sr_robot_msgs::GetFastGraspFromBoundingBoxRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sr_robot_msgs::GetFastGraspFromBoundingBoxRequest> should match 
// service_traits::DataType< ::sr_robot_msgs::GetFastGraspFromBoundingBox > 
template<>
struct DataType< ::sr_robot_msgs::GetFastGraspFromBoundingBoxRequest>
{
  static const char* value()
  {
    return DataType< ::sr_robot_msgs::GetFastGraspFromBoundingBox >::value();
  }
  static const char* value(const ::sr_robot_msgs::GetFastGraspFromBoundingBoxRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sr_robot_msgs::GetFastGraspFromBoundingBoxResponse> should match 
// service_traits::MD5Sum< ::sr_robot_msgs::GetFastGraspFromBoundingBox > 
template<>
struct MD5Sum< ::sr_robot_msgs::GetFastGraspFromBoundingBoxResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sr_robot_msgs::GetFastGraspFromBoundingBox >::value();
  }
  static const char* value(const ::sr_robot_msgs::GetFastGraspFromBoundingBoxResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sr_robot_msgs::GetFastGraspFromBoundingBoxResponse> should match 
// service_traits::DataType< ::sr_robot_msgs::GetFastGraspFromBoundingBox > 
template<>
struct DataType< ::sr_robot_msgs::GetFastGraspFromBoundingBoxResponse>
{
  static const char* value()
  {
    return DataType< ::sr_robot_msgs::GetFastGraspFromBoundingBox >::value();
  }
  static const char* value(const ::sr_robot_msgs::GetFastGraspFromBoundingBoxResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SR_ROBOT_MSGS_MESSAGE_GETFASTGRASPFROMBOUNDINGBOX_H
