// Generated by gencpp from file sr_robot_msgs/ListNamedTrajectories.msg
// DO NOT EDIT!


#ifndef SR_ROBOT_MSGS_MESSAGE_LISTNAMEDTRAJECTORIES_H
#define SR_ROBOT_MSGS_MESSAGE_LISTNAMEDTRAJECTORIES_H

#include <ros/service_traits.h>


#include <sr_robot_msgs/ListNamedTrajectoriesRequest.h>
#include <sr_robot_msgs/ListNamedTrajectoriesResponse.h>


namespace sr_robot_msgs
{

struct ListNamedTrajectories
{

typedef ListNamedTrajectoriesRequest Request;
typedef ListNamedTrajectoriesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ListNamedTrajectories
} // namespace sr_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sr_robot_msgs::ListNamedTrajectories > {
  static const char* value()
  {
    return "dc7ae3609524b18034e49294a4ce670e";
  }

  static const char* value(const ::sr_robot_msgs::ListNamedTrajectories&) { return value(); }
};

template<>
struct DataType< ::sr_robot_msgs::ListNamedTrajectories > {
  static const char* value()
  {
    return "sr_robot_msgs/ListNamedTrajectories";
  }

  static const char* value(const ::sr_robot_msgs::ListNamedTrajectories&) { return value(); }
};


// service_traits::MD5Sum< ::sr_robot_msgs::ListNamedTrajectoriesRequest> should match 
// service_traits::MD5Sum< ::sr_robot_msgs::ListNamedTrajectories > 
template<>
struct MD5Sum< ::sr_robot_msgs::ListNamedTrajectoriesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sr_robot_msgs::ListNamedTrajectories >::value();
  }
  static const char* value(const ::sr_robot_msgs::ListNamedTrajectoriesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sr_robot_msgs::ListNamedTrajectoriesRequest> should match 
// service_traits::DataType< ::sr_robot_msgs::ListNamedTrajectories > 
template<>
struct DataType< ::sr_robot_msgs::ListNamedTrajectoriesRequest>
{
  static const char* value()
  {
    return DataType< ::sr_robot_msgs::ListNamedTrajectories >::value();
  }
  static const char* value(const ::sr_robot_msgs::ListNamedTrajectoriesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sr_robot_msgs::ListNamedTrajectoriesResponse> should match 
// service_traits::MD5Sum< ::sr_robot_msgs::ListNamedTrajectories > 
template<>
struct MD5Sum< ::sr_robot_msgs::ListNamedTrajectoriesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sr_robot_msgs::ListNamedTrajectories >::value();
  }
  static const char* value(const ::sr_robot_msgs::ListNamedTrajectoriesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sr_robot_msgs::ListNamedTrajectoriesResponse> should match 
// service_traits::DataType< ::sr_robot_msgs::ListNamedTrajectories > 
template<>
struct DataType< ::sr_robot_msgs::ListNamedTrajectoriesResponse>
{
  static const char* value()
  {
    return DataType< ::sr_robot_msgs::ListNamedTrajectories >::value();
  }
  static const char* value(const ::sr_robot_msgs::ListNamedTrajectoriesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SR_ROBOT_MSGS_MESSAGE_LISTNAMEDTRAJECTORIES_H
