// Generated by gencpp from file sr_robot_msgs/RobotTeachMode.msg
// DO NOT EDIT!


#ifndef SR_ROBOT_MSGS_MESSAGE_ROBOTTEACHMODE_H
#define SR_ROBOT_MSGS_MESSAGE_ROBOTTEACHMODE_H

#include <ros/service_traits.h>


#include <sr_robot_msgs/RobotTeachModeRequest.h>
#include <sr_robot_msgs/RobotTeachModeResponse.h>


namespace sr_robot_msgs
{

struct RobotTeachMode
{

typedef RobotTeachModeRequest Request;
typedef RobotTeachModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotTeachMode
} // namespace sr_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sr_robot_msgs::RobotTeachMode > {
  static const char* value()
  {
    return "c6613d1d4bc3ca4c55986e93b2eaff93";
  }

  static const char* value(const ::sr_robot_msgs::RobotTeachMode&) { return value(); }
};

template<>
struct DataType< ::sr_robot_msgs::RobotTeachMode > {
  static const char* value()
  {
    return "sr_robot_msgs/RobotTeachMode";
  }

  static const char* value(const ::sr_robot_msgs::RobotTeachMode&) { return value(); }
};


// service_traits::MD5Sum< ::sr_robot_msgs::RobotTeachModeRequest> should match 
// service_traits::MD5Sum< ::sr_robot_msgs::RobotTeachMode > 
template<>
struct MD5Sum< ::sr_robot_msgs::RobotTeachModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sr_robot_msgs::RobotTeachMode >::value();
  }
  static const char* value(const ::sr_robot_msgs::RobotTeachModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sr_robot_msgs::RobotTeachModeRequest> should match 
// service_traits::DataType< ::sr_robot_msgs::RobotTeachMode > 
template<>
struct DataType< ::sr_robot_msgs::RobotTeachModeRequest>
{
  static const char* value()
  {
    return DataType< ::sr_robot_msgs::RobotTeachMode >::value();
  }
  static const char* value(const ::sr_robot_msgs::RobotTeachModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sr_robot_msgs::RobotTeachModeResponse> should match 
// service_traits::MD5Sum< ::sr_robot_msgs::RobotTeachMode > 
template<>
struct MD5Sum< ::sr_robot_msgs::RobotTeachModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sr_robot_msgs::RobotTeachMode >::value();
  }
  static const char* value(const ::sr_robot_msgs::RobotTeachModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sr_robot_msgs::RobotTeachModeResponse> should match 
// service_traits::DataType< ::sr_robot_msgs::RobotTeachMode > 
template<>
struct DataType< ::sr_robot_msgs::RobotTeachModeResponse>
{
  static const char* value()
  {
    return DataType< ::sr_robot_msgs::RobotTeachMode >::value();
  }
  static const char* value(const ::sr_robot_msgs::RobotTeachModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SR_ROBOT_MSGS_MESSAGE_ROBOTTEACHMODE_H
