(cl:defpackage AW_hand_service-srv
  (:use )
  (:export
   "MOVEOBJ"
   "<MOVEOBJ-REQUEST>"
   "MOVEOBJ-REQUEST"
   "<MOVEOBJ-RESPONSE>"
   "MOVEOBJ-RESPONSE"
   "MOVEROBOT"
   "<MOVEROBOT-REQUEST>"
   "MOVEROBOT-REQUEST"
   "<MOVEROBOT-RESPONSE>"
   "MOVEROBOT-RESPONSE"
  ))

