controller_list:
  - name: fake_first_finger_controller
    joints:
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7
      - rh_WRJ2
      - rh_WRJ1
      - rh_FFJ4
      - rh_FFJ3
      - rh_FFJ2
      - rh_FFJ1
  - name: fake_middel_finger_controller
    joints:
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7
      - rh_WRJ2
      - rh_WRJ1
      - rh_MFJ4
      - rh_MFJ3
      - rh_MFJ2
      - rh_MFJ1
  - name: fake_iwaa_controller
    joints:
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7
  - name: fake_hand_controller
    joints:
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7
      - rh_WRJ2
      - rh_WRJ1
      - rh_FFJ4
      - rh_FFJ3
      - rh_FFJ2
      - rh_FFJ1
      - rh_MFJ4
      - rh_MFJ3
      - rh_MFJ2
      - rh_MFJ1