FROM shadowrobot/dexterous-hand:kinetic
#****************Setting up user *********************


#******************** Installing extra packages for ros************************



#*********************************************************************
CMD /bin/bash
