training_description: ""
max_episode_steps: 5000

actionRepeat_reward_mode: "tele"
adaptive_action_reperate: None

reward_mode: 1
actionRepeat: 1
action_mode: "jointControl"
random_start: False
obs_mode: "palm_pos_orn"
reward_obs_mode: "palm_world"
AW_mode: 1
AW_radius : [0.3,0.4]
batch_size: 64
feature_extractionLayers: 
  layers: [64,64,64]
  type: dense
  conv:
    num_filters:
    kernel_size:
    strides:
DenseLayer: 
  layers: [64]
  type: dense
  LSTM:
    number_of_lstm_cells: 200

n_epoch: 10

lr: 1e-4

discount: 0.99
lam: 0.95
horizon: 2048

enable_gae: True


slack_channel: rl_server



