(cl:in-package sr_robot_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          SET_VALVE_MUSCLE_0-VAL
          SET_VALVE_MUSCLE_0
          SET_VALVE_MUSCLE_1-VAL
          SET_VALVE_MUSCLE_1
          SET_DURATION_MUSCLE_0-VAL
          SET_DURATION_MUSCLE_0
          SET_DURATION_MUSCLE_1-VAL
          SET_DURATION_MUSCLE_1
          CURRENT_VALVE_MUSCLE_0-VAL
          CURRENT_VALVE_MUSCLE_0
          CURRENT_VALVE_MUSCLE_1-VAL
          CURRENT_VALVE_MUSCLE_1
          CURRENT_DURATION_MUSCLE_0-VAL
          CURRENT_DURATION_MUSCLE_0
          CURRENT_DURATION_MUSCLE_1-VAL
          CURRENT_DURATION_MUSCLE_1
          PACKED_VALVE-VAL
          PACKED_VALVE
          MUSCLE_PRESSURE_0-VAL
          MUSCLE_PRESSURE_0
          MUSCLE_PRESSURE_1-VAL
          MUSCLE_PRESSURE_1
          TIME_STEP-VAL
          TIME_STEP
))