(cl:in-package sr_robot_msgs-msg)
(cl:export '(MOTOR_ID-VAL
          MOTOR_ID
          ENABLE_BACKLASH_COMPENSATION-VAL
          ENABLE_BACKLASH_COMPENSATION
          INCREASE_SGL_TRACKING-VAL
          INCREASE_SGL_TRACKING
          DECREASE_SGL_TRACKING-VAL
          DECREASE_SGL_TRACKING
          INCREASE_SGR_TRACKING-VAL
          INCREASE_SGR_TRACKING
          DECREASE_SGR_TRACKING-VAL
          DECREASE_SGR_TRACKING
          INITIATE_JIGGLING-VAL
          INITIATE_JIGGLING
          WRITE_CONFIG_TO_EEPROM-VAL
          WRITE_CONFIG_TO_EEPROM
))