(cl:in-package sr_robot_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          SENSORS-VAL
          SENSORS
          MOTOR_DATA_TYPE-VAL
          MOTOR_DATA_TYPE
          WHICH_MOTORS-VAL
          WHICH_MOTORS
          WHICH_MOTOR_DATA_ARRIVED-VAL
          WHICH_MOTOR_DATA_ARRIVED
          WHICH_MOTOR_DATA_HAD_ERRORS-VAL
          WHICH_MOTOR_DATA_HAD_ERRORS
          MOTOR_DATA_PACKET_TORQUE-VAL
          MOTOR_DATA_PACKET_TORQUE
          MOTOR_DATA_PACKET_MISC-VAL
          MOTOR_DATA_PACKET_MISC
          TACTILE_DATA_TYPE-VAL
          TACTILE_DATA_TYPE
          TACTILE_DATA_VALID-VAL
          TACTILE_DATA_VALID
          TACTILE-VAL
          TACTILE
          IDLE_TIME_US-VAL
          IDLE_TIME_US
))