(cl:in-package sr_robot_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          SET_POINT-VAL
          SET_POINT
          PROCESS_VALUE-VAL
          PROCESS_VALUE
          PROCESS_VALUE_DOT-VAL
          PROCESS_VALUE_DOT
          ERROR-VAL
          ERROR
          TIME_STEP-VAL
          TIME_STEP
          PSEUDO_COMMAND-VAL
          PSEUDO_COMMAND
          VALVE_MUSCLE_0-VAL
          VALVE_MUSCLE_0
          VALVE_MUSCLE_1-VAL
          VALVE_MUSCLE_1
          PACKED_VALVE-VAL
          PACKED_VALVE
          MUSCLE_PRESSURE_0-VAL
          MUSCLE_PRESSURE_0
          MUSCLE_PRESSURE_1-VAL
          MUSCLE_PRESSURE_1
          P-VAL
          P
          I-VAL
          I
          D-VAL
          D
          I_CLAMP-VAL
          I_CLAMP
))