(cl:in-package sr_robot_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          SET_POINT-VAL
          SET_POINT
          PROCESS_VALUE-VAL
          PROCESS_VALUE
          PROCESS_VALUE_DOT-VAL
          PROCESS_VALUE_DOT
          COMMANDED_VELOCITY-VAL
          COMMANDED_VELOCITY
          ERROR-VAL
          ERROR
          TIME_STEP-VAL
          TIME_STEP
          COMMAND-VAL
          COMMAND
          MEASURED_EFFORT-VAL
          MEASURED_EFFORT
          FRICTION_COMPENSATION-VAL
          FRICTION_COMPENSATION
          POSITION_P-VAL
          POSITION_P
          POSITION_I-VAL
          POSITION_I
          POSITION_D-VAL
          POSITION_D
          POSITION_I_CLAMP-VAL
          POSITION_I_CLAMP
          VELOCITY_P-VAL
          VELOCITY_P
          VELOCITY_I-VAL
          VELOCITY_I
          VELOCITY_D-VAL
          VELOCITY_D
          VELOCITY_I_CLAMP-VAL
          VELOCITY_I_CLAMP
))