// Generated by gencpp from file cw3_helper/ChangeCollisionObjectResponse.msg
// DO NOT EDIT!


#ifndef CW3_HELPER_MESSAGE_CHANGECOLLISIONOBJECTRESPONSE_H
#define CW3_HELPER_MESSAGE_CHANGECOLLISIONOBJECTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cw3_helper
{
template <class ContainerAllocator>
struct ChangeCollisionObjectResponse_
{
  typedef ChangeCollisionObjectResponse_<ContainerAllocator> Type;

  ChangeCollisionObjectResponse_()
    : success(false)  {
    }
  ChangeCollisionObjectResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::cw3_helper::ChangeCollisionObjectResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cw3_helper::ChangeCollisionObjectResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ChangeCollisionObjectResponse_

typedef ::cw3_helper::ChangeCollisionObjectResponse_<std::allocator<void> > ChangeCollisionObjectResponse;

typedef boost::shared_ptr< ::cw3_helper::ChangeCollisionObjectResponse > ChangeCollisionObjectResponsePtr;
typedef boost::shared_ptr< ::cw3_helper::ChangeCollisionObjectResponse const> ChangeCollisionObjectResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cw3_helper::ChangeCollisionObjectResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cw3_helper::ChangeCollisionObjectResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cw3_helper

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cw3_helper::ChangeCollisionObjectResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cw3_helper::ChangeCollisionObjectResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cw3_helper::ChangeCollisionObjectResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cw3_helper::ChangeCollisionObjectResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cw3_helper::ChangeCollisionObjectResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cw3_helper::ChangeCollisionObjectResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cw3_helper::ChangeCollisionObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::cw3_helper::ChangeCollisionObjectResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::cw3_helper::ChangeCollisionObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cw3_helper/ChangeCollisionObjectResponse";
  }

  static const char* value(const ::cw3_helper::ChangeCollisionObjectResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cw3_helper::ChangeCollisionObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
";
  }

  static const char* value(const ::cw3_helper::ChangeCollisionObjectResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cw3_helper::ChangeCollisionObjectResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChangeCollisionObjectResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cw3_helper::ChangeCollisionObjectResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cw3_helper::ChangeCollisionObjectResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CW3_HELPER_MESSAGE_CHANGECOLLISIONOBJECTRESPONSE_H
